# /Users/medaminebentaieb/Docker_files/Laravel_Docker/docker-compose.yml

services:
  # Nginx Service for Laravel Backend
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:80"    # Laravel accessible via http://localhost:8000
      - "8001:443"   # HTTPS (if needed) accessible via https://localhost:8001
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d    # Nginx configuration
      - ./nginx/logs:/var/log/nginx          # Nginx logs
      - ./laravel/src:/var/www                # Laravel application code
    depends_on:
      - laravel
    networks:
      - app-network

  # Laravel Backend Service
  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    container_name: laravel
    restart: unless-stopped
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_KEY: ${APP_KEY}
      APP_URL: ${APP_URL}
      FRONTEND_URL: ${FRONTEND_URL}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MAIL_MAILER: ${MAIL_MAILER}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
      JWT_SECRET: ${JWT_SECRET}
      KONNECT_URL: ${KONNECT_URL}
      KONNECT_API_KEY: ${KONNECT_API_KEY}
      LOG_CHANNEL: ${LOG_CHANNEL}
      LOG_DEPRECATIONS_CHANNEL: ${LOG_DEPRECATIONS_CHANNEL}
      LOG_LEVEL: ${LOG_LEVEL}
      BROADCAST_DRIVER: ${BROADCAST_DRIVER}
      CACHE_DRIVER: ${CACHE_DRIVER}
      FILESYSTEM_DISK: ${FILESYSTEM_DISK}
      QUEUE_CONNECTION: ${QUEUE_CONNECTION}
      SESSION_DRIVER: ${SESSION_DRIVER}
      SESSION_LIFETIME: ${SESSION_LIFETIME}
      MEMCACHED_HOST: ${MEMCACHED_HOST}
    volumes:
      - ./laravel/src:/var/www                # Laravel application code
    depends_on:
      - db
    networks:
      - app-network

  # MySQL Database Service
  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql              # Persist MySQL data
    networks:
      - app-network

  # phpMyAdmin Service using linuxserver/phpmyadmin
  phpmyadmin:
    image: linuxserver/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PUID: 1000                # Replace with your user ID
      PGID: 1000                # Replace with your group ID
      TZ: "Europe/London"       # Replace with your timezone
      UPLOAD_LIMIT: 100M        # Optional: Set upload limit
    ports:
      - "8080:80"                # Access via http://localhost:8080
    volumes:
      - ./phpmyadmin/config:/config   # Configuration data
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
